language: java

jdk: oraclejdk8


before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y graphviz

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - chmod u+x docs/deploy.sh
  - wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
  - tar xvf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz

script: 
 - ./docs/deploy.sh
 - mvn verify -Dgpg.skip=true

env:
  global:
  - ENCRYPTION_LABEL: "7345bb60ed89"
  matrix:	
  - TRAVIS_NODE_VERSION="5"
  
